-- =====================================================
-- PHẦN 1: CÀI ĐẶT MÔI TRƯỜNG & QUẢN LÝ TRUY CẬP
-- TPC-H Analytics Project
-- =====================================================

-- =====================================================
-- 1.1 TẠO ROLES VÀ PHÂN QUYỀN
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- Tạo các roles cho dự án
CREATE ROLE IF NOT EXISTS TPCH_ADMIN 
    COMMENT = 'Quản trị toàn bộ dự án TPC-H Analytics';

CREATE ROLE IF NOT EXISTS TPCH_DEVELOPER 
    COMMENT = 'Developer: Load data, transform, và phát triển pipeline';

CREATE ROLE IF NOT EXISTS TPCH_ANALYST 
    COMMENT = 'Analyst: Query data và tạo reports';

CREATE ROLE IF NOT EXISTS TPCH_VIEWER 
    COMMENT = 'Viewer: Chỉ được xem reports';

-- Thiết lập role hierarchy
GRANT ROLE TPCH_VIEWER TO ROLE TPCH_ANALYST;
GRANT ROLE TPCH_ANALYST TO ROLE TPCH_DEVELOPER;
GRANT ROLE TPCH_DEVELOPER TO ROLE TPCH_ADMIN;
GRANT ROLE TPCH_ADMIN TO ROLE ACCOUNTADMIN;

-- Grant SYSADMIN role cho TPCH_ADMIN để quản lý warehouses
GRANT ROLE SYSADMIN TO ROLE TPCH_ADMIN;

SHOW ROLES LIKE 'TPCH%';

-- =====================================================
-- 1.2 TẠO DATABASE VÀ SCHEMAS
-- =====================================================

USE ROLE TPCH_ADMIN;

-- Tạo database cho dự án
CREATE DATABASE IF NOT EXISTS TPCH_ANALYTICS_DB
    COMMENT = 'Database chính cho TPC-H Analytics Project';

USE DATABASE TPCH_ANALYTICS_DB;

-- Tạo các schemas theo Medallion Architecture
CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Bronze Layer - Dữ liệu gốc từ files (Raw data)';

CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'Silver Layer - Dữ liệu đã biến đổi và làm sạch';

CREATE SCHEMA IF NOT EXISTS REPORTS
    COMMENT = 'Gold Layer - Báo cáo và metrics cuối cùng';

CREATE SCHEMA IF NOT EXISTS UDFS
    COMMENT = 'User-defined functions và stored procedures';

SHOW SCHEMAS IN DATABASE TPCH_ANALYTICS_DB;

-- =====================================================
-- Grant quyền trên Database và Schemas
-- =====================================================

-- TPCH_ADMIN: Full access
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ADMIN;

-- TPCH_DEVELOPER: Create, modify objects in all schemas
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE PROCEDURE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;
GRANT USAGE, CREATE FUNCTION, CREATE PROCEDURE ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;

-- TPCH_ANALYST: Query access
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;

-- TPCH_VIEWER: Read-only access to REPORTS only
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;

-- =====================================================
-- Tạo Warehouse cho project
-- =====================================================

USE ROLE TPCH_ADMIN;

CREATE WAREHOUSE IF NOT EXISTS TPCH_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = FALSE
    COMMENT = 'Warehouse cho TPC-H Analytics Project';

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE TPCH_WH TO ROLE TPCH_ADMIN;
GRANT USAGE ON WAREHOUSE TPCH_WH TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON WAREHOUSE TPCH_WH TO ROLE TPCH_ANALYST;
GRANT USAGE ON WAREHOUSE TPCH_WH TO ROLE TPCH_VIEWER;

USE WAREHOUSE TPCH_WH;

-- =====================================================
-- 1.3 TẠO STAGES VÀ FILE FORMATS
-- =====================================================

USE ROLE TPCH_DEVELOPER;
USE DATABASE TPCH_ANALYTICS_DB;
USE SCHEMA STAGING;

-- Tạo internal stage cho TPC-H data files
CREATE OR REPLACE STAGE TPCH_DATA_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage chứa TPC-H data files (.csv)';

-- Tạo file format cho CSV files
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = '|'
    SKIP_HEADER = 0
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE'
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    ESCAPE = 'NONE'
    ESCAPE_UNENCLOSED_FIELD = 'NONE'
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    COMMENT = 'CSV format cho TPC-H data files';

-- Grant quyền trên stage và file format
-- Note: Internal stages require READ/WRITE instead of USAGE
GRANT READ, WRITE ON STAGE TPCH_DATA_STAGE TO ROLE TPCH_ADMIN;
GRANT READ, WRITE ON STAGE TPCH_DATA_STAGE TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON FILE FORMAT CSV_FORMAT TO ROLE TPCH_ADMIN;
GRANT USAGE ON FILE FORMAT CSV_FORMAT TO ROLE TPCH_DEVELOPER;

SHOW STAGES;
SHOW FILE FORMATS;

-- =====================================================
-- 1.4 TẠO CÁC BẢNG RAW (BRONZE LAYER)
-- =====================================================

USE SCHEMA STAGING;

-- Bảng 1: REGION
CREATE OR REPLACE TABLE REGION (
    R_REGIONKEY NUMBER(38,0) PRIMARY KEY,
    R_NAME VARCHAR(25) NOT NULL,
    R_COMMENT VARCHAR(152),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Bảng 2: NATION
CREATE OR REPLACE TABLE NATION (
    N_NATIONKEY NUMBER(38,0) PRIMARY KEY,
    N_NAME VARCHAR(25) NOT NULL,
    N_REGIONKEY NUMBER(38,0) NOT NULL,
    N_COMMENT VARCHAR(152),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);

-- Bảng 3: CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER (
    C_CUSTKEY NUMBER(38,0) PRIMARY KEY,
    C_NAME VARCHAR(25) NOT NULL,
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY NUMBER(38,0) NOT NULL,
    C_PHONE VARCHAR(15),
    C_ACCTBAL NUMBER(12,2),
    C_MKTSEGMENT VARCHAR(10),
    C_COMMENT VARCHAR(117),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

-- Bảng 4: SUPPLIER
CREATE OR REPLACE TABLE SUPPLIER (
    S_SUPPKEY NUMBER(38,0) PRIMARY KEY,
    S_NAME VARCHAR(25) NOT NULL,
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY NUMBER(38,0) NOT NULL,
    S_PHONE VARCHAR(15),
    S_ACCTBAL NUMBER(12,2),
    S_COMMENT VARCHAR(101),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

-- Bảng 5: PART
CREATE OR REPLACE TABLE PART (
    P_PARTKEY NUMBER(38,0) PRIMARY KEY,
    P_NAME VARCHAR(55) NOT NULL,
    P_MFGR VARCHAR(25),
    P_BRAND VARCHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE NUMBER(38,0),
    P_CONTAINER VARCHAR(10),
    P_RETAILPRICE NUMBER(12,2),
    P_COMMENT VARCHAR(23),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Bảng 6: PARTSUPP
CREATE OR REPLACE TABLE PARTSUPP (
    PS_PARTKEY NUMBER(38,0),
    PS_SUPPKEY NUMBER(38,0),
    PS_AVAILQTY NUMBER(38,0),
    PS_SUPPLYCOST NUMBER(12,2),
    PS_COMMENT VARCHAR(199),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
    FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);

-- Bảng 7: ORDERS
CREATE OR REPLACE TABLE ORDERS (
    O_ORDERKEY NUMBER(38,0) PRIMARY KEY,
    O_CUSTKEY NUMBER(38,0) NOT NULL,
    O_ORDERSTATUS VARCHAR(1),
    O_TOTALPRICE NUMBER(12,2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY VARCHAR(15),
    O_CLERK VARCHAR(15),
    O_SHIPPRIORITY NUMBER(38,0),
    O_COMMENT VARCHAR(79),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);

-- Bảng 8: LINEITEM
CREATE OR REPLACE TABLE LINEITEM (
    L_ORDERKEY NUMBER(38,0),
    L_PARTKEY NUMBER(38,0),
    L_SUPPKEY NUMBER(38,0),
    L_LINENUMBER NUMBER(38,0),
    L_QUANTITY NUMBER(12,2),
    L_EXTENDEDPRICE NUMBER(12,2),
    L_DISCOUNT NUMBER(12,2),
    L_TAX NUMBER(12,2),
    L_RETURNFLAG VARCHAR(1),
    L_LINESTATUS VARCHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT VARCHAR(25),
    L_SHIPMODE VARCHAR(10),
    L_COMMENT VARCHAR(44),
    -- Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);

SHOW TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- =====================================================
-- 1.5 LOAD DỮ LIỆU TỪ SNOWFLAKE SAMPLE DATA
-- =====================================================

-- Lưu ý: Vì TPC-H data có sẵn trong SNOWFLAKE_SAMPLE_DATA,
-- chúng ta sẽ load trực tiếp từ đó thay vì upload files

USE ROLE TPCH_DEVELOPER;
USE DATABASE TPCH_ANALYTICS_DB;
USE SCHEMA STAGING;
USE WAREHOUSE TPCH_WH;

-- Load REGION
INSERT INTO REGION (R_REGIONKEY, R_NAME, R_COMMENT)
SELECT R_REGIONKEY, R_NAME, R_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

-- Load NATION
INSERT INTO NATION (N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT)
SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

-- Load CUSTOMER
INSERT INTO CUSTOMER (C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT)
SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- Load SUPPLIER
INSERT INTO SUPPLIER (S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT)
SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

-- Load PART
INSERT INTO PART (P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT)
SELECT P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

-- Load PARTSUPP
INSERT INTO PARTSUPP (PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST, PS_COMMENT)
SELECT PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST, PS_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

-- Load ORDERS
INSERT INTO ORDERS (O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY, O_COMMENT)
SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY, O_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

-- Load LINEITEM
INSERT INTO LINEITEM (L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, 
                      L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT)
SELECT L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX,
       L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

-- =====================================================
-- 1.6 KIỂM TRA DỮ LIỆU VÀ PHÂN QUYỀN
-- =====================================================

-- Kiểm tra số lượng records trong mỗi bảng
SELECT 'REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM REGION
UNION ALL
SELECT 'NATION', COUNT(*) FROM NATION
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER
UNION ALL
SELECT 'SUPPLIER', COUNT(*) FROM SUPPLIER
UNION ALL
SELECT 'PART', COUNT(*) FROM PART
UNION ALL
SELECT 'PARTSUPP', COUNT(*) FROM PARTSUPP
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'LINEITEM', COUNT(*) FROM LINEITEM
ORDER BY TABLE_NAME;

-- Kiểm tra sample data
SELECT 'REGION Sample' AS INFO;
SELECT * FROM REGION LIMIT 5;

SELECT 'NATION Sample' AS INFO;
SELECT * FROM NATION LIMIT 5;

SELECT 'CUSTOMER Sample' AS INFO;
SELECT * FROM CUSTOMER LIMIT 5;

SELECT 'ORDERS Sample' AS INFO;
SELECT * FROM ORDERS LIMIT 5;

-- Kiểm tra relationships
SELECT 
    O.O_ORDERKEY,
    O.O_ORDERDATE,
    O.O_TOTALPRICE,
    C.C_NAME AS CUSTOMER_NAME,
    N.N_NAME AS NATION,
    R.R_NAME AS REGION
FROM ORDERS O
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
LIMIT 10;

-- =====================================================
-- KIỂM TRA QUYỀN TRUY CẬP
-- =====================================================

-- Test với role TPCH_ANALYST (có quyền SELECT)
USE ROLE TPCH_ANALYST;
SELECT COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.ORDERS;

-- Test với role TPCH_VIEWER (không có quyền truy cập STAGING)
USE ROLE TPCH_VIEWER;
-- Câu lệnh sau sẽ fail vì VIEWER không có quyền truy cập STAGING schema
-- SELECT COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.ORDERS;

-- Switch back to admin
USE ROLE TPCH_ADMIN;

-- =====================================================
-- TỔNG KẾT
-- =====================================================

SELECT '✅ PHẦN 1 HOÀN THÀNH!' AS STATUS;
SELECT 'Database, Schemas, Roles, Stages, và Tables đã được tạo thành công!' AS MESSAGE;
SELECT 'Dữ liệu TPC-H đã được load vào Bronze Layer (STAGING schema)' AS MESSAGE;

-- Hiển thị tổng quan hệ thống
SELECT 
    'ROLES' AS COMPONENT,
    LISTAGG(ROLE_NAME, ', ') AS DETAILS
FROM (
    SELECT NAME AS ROLE_NAME FROM SNOWFLAKE.ACCOUNT_USAGE.ROLES 
    WHERE NAME LIKE 'TPCH%'
    ORDER BY NAME
) AS role_list
UNION ALL
SELECT 
    'SCHEMAS',
    LISTAGG(SCHEMA_NAME, ', ')
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('STAGING', 'ANALYTICS', 'REPORTS', 'UDFS')
UNION ALL
SELECT 
    'TABLES',
    COUNT(*)::VARCHAR
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING';


-- Chạy query này để kiểm tra
SHOW DATABASES LIKE 'TPCH_ANALYTICS_DB';
SHOW ROLES LIKE 'TPCH%';
SHOW TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- Đếm số dòng trong bảng ORDERS
SELECT COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.ORDERS;
-- Kết quả: 1,500,000 rows

-- Xem tổng quan database structure với row counts
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    BYTES / (1024*1024) AS SIZE_MB,
    CREATED,
    LAST_ALTERED
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG = 'TPCH_ANALYTICS_DB'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- =====================================================
-- SIMPLE ROLE & PERMISSION OVERVIEW
-- =====================================================

-- 1. Show all TPCH roles
SELECT 'PROJECT ROLES' AS SECTION;
SHOW ROLES LIKE 'TPCH%';

-- 2. Show role hierarchy
SELECT 'ROLE HIERARCHY' AS SECTION;
SHOW GRANTS OF ROLE TPCH_VIEWER;   -- Shows TPCH_VIEWER granted to TPCH_ANALYST
SHOW GRANTS OF ROLE TPCH_ANALYST;  -- Shows TPCH_ANALYST granted to TPCH_DEVELOPER
SHOW GRANTS OF ROLE TPCH_DEVELOPER; -- Shows TPCH_DEVELOPER granted to TPCH_ADMIN
SHOW GRANTS OF ROLE TPCH_ADMIN; 


SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    CREATED,
    LAST_ALTERED,
    DATEDIFF(DAY, CREATED, LAST_ALTERED) AS DAYS_SINCE_CREATION,
    ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG = 'TPCH_ANALYTICS_DB'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY LAST_ALTERED DESC;


-- Tóm tắt quyền theo role
SELECT 
    GRANTEE_NAME AS ROLE,
    GRANTED_ON AS OBJECT_TYPE,
    COUNT(*) AS COUNT,
    LISTAGG(DISTINCT PRIVILEGE, ', ') AS PRIVILEGES
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE GRANTEE_NAME IN ('TPCH_ADMIN', 'TPCH_DEVELOPER', 'TPCH_ANALYST', 'TPCH_VIEWER')
    AND DELETED_ON IS NULL
GROUP BY GRANTEE_NAME, GRANTED_ON
ORDER BY GRANTEE_NAME, GRANTED_ON;

